### ISSUE TITLE
Add New Entity For Mode

### ISSUE THREAD

**Issue by iwarp** [scottyphillips/mitsubishi_hass#32]
Hi,
I would like to be able to visualize using the Dashboard History Graph card when the unit is in which operating mode, like we can do with the fan speed. I wanting to build an automation that will switch from heat to fan mode when the fire is on, then return to heat once the temperature drops.

![image](https://user-images.githubusercontent.com/20696463/129988181-802f8702-a6b2-4d63-ae43-499513e75fa0.png)

**Comment by scottyphillips** [comment]
Hi, 

This can be accomplished with a template sensor.

```
sensor:
  - platform: template
    sensors: 
      climate_state:
        value_template: "{{ state_attr('climate.mitsubishi_ducted', 'hvac_action') }}"  
        friendly_name: 'HVAC Action' 
```
